[colors.primary]
  # Default colors
    background= '0x1e2127'
    foreground= '0xabb2bf'

  # Normal colors
[colors.normal]
    black=   '0x1e2127'
    red=     '0xe06c75'
    green=   '0x98c379'
    yellow=  '0xd19a66'
    blue=    '0x61afef'
    magenta= '0xc678dd'
    cyan=    '0x56b6c2'
    white=   '0x828791'

  # Bright colors
[colors.bright]
    black=   '0x5c6370'
    red=     '0xe06c75'
    green=   '0x98c379'
    yellow=  '0xd19a66'
    blue=    '0x61afef'
    magenta= '0xc678dd'
    cyan=    '0x56b6c2'
    white=   '0xe6efff'

[colors.dim]
    black=   '0x1e2127'
    red=     '0xe06c75'
    green=   '0x98c379'
    yellow=  '0xd19a66'
    blue=    '0x61afef'
    magenta= '0xc678dd'
    cyan=    '0x56b6c2'
    white=   '0x828791'


[font]
    normal = { family = "NotoMonoNerdFont", style = "Regular" }
    size = 12.0

[window]
    opacity = 0.98
    blur = true
    dynamic_title = true

[shell]
    program = "/usr/bin/tmux"
    background = '0x2D2A2E'
    foreground = '0xfff1f3'

  # Normal colors
[colors.normal]
    black = '0x2c2525'
    red = '0xfd6883'
    green = '0xadda78'
    yellow = '0xf9cc6c'
    blue = '0xf38d70'
    magenta = '0xa8a9eb'
    cyan = '0x85dacc'
    white = '0xfff1f3'

  # Bright colors
[colors.bright]
    black = '0x72696a'
    red = '0xfd6883'
    green = '0xadda78'
    yellow = '0xf9cc6c'
    blue = '0xf38d70'
    magenta = '0xa8a9eb'
    cyan = '0x85dacc'
    white = '0xfff1f3'

[window]
    decorations = "Buttonless"
    opacity = 0.92
