[colors.primary]
  # Default colors
    background = '0x2D2A2E'
    foreground = '0xfff1f3'

  # Normal colors
[colors.normal]
    black = '0x2c2525'
    red = '0xfd6883'
    green = '0xadda78'
    yellow = '0xf9cc6c'
    blue = '0xf38d70'
    magenta = '0xa8a9eb'
    cyan = '0x85dacc'
    white = '0xfff1f3'

  # Bright colors
[colors.bright]
    black = '0x72696a'
    red = '0xfd6883'
    green = '0xadda78'
    yellow = '0xf9cc6c'
    blue = '0xf38d70'
    magenta = '0xa8a9eb'
    cyan = '0x85dacc'
    white = '0xfff1f3'


[font]
    normal = { family = "Monaco", style = "Regular" }
    size = 22.0


[window]
    opacity = 0.92

